version: '3.8'
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
            - ./:/var/www/
        ports:
            - 9000:80
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/


    mysql:
        image: mysql:8.3
        environment:
            MYSQL_ROOT_PASSWORD: root
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./tmp/db:/var/lib/mysql
        depends_on:
            - phpmyadmin

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8000:80
        environment:
            - PMA_ARBITRARY=1
